server:
  port: 8089
spring:
  application:
    name: dlx-receiver-msg #主题交换机
  #配置rabbitmq
  rabbitmq:
#    host: 192.168.18.131 #rabbitmq的地址
    host: 47.120.35.124 #rabbitmq的地址
    port: 5672 #rabbitmq的端口号
    username: admin #rabbitmq的用户名
    password: 123456 #rabbitmq的密码
    virtual-host: dreamcatcher #rabbitmq的虚拟主机

