server:
  port: 8080
spring:
  application:
    name: delay-learn4 #主题交换机
  #配置rabbitmq
  rabbitmq:
#    host: 192.168.18.131 #rabbitmq的地址
    host: 47.120.35.124
    port: 5672 #rabbitmq的端口号
    username: admin #rabbitmq的用户名
    password: 123456 #rabbitmq的密码
    virtual-host: dreamcatcher #rabbitmq的虚拟主机

my:
  exchangeName: exchange.delay.4 #交换机名称 延迟交换机
  queueDelayName: queue.delay.4 #延迟队列  不需要死信队列
