server:
  port: 8080
spring:
  application:
    name: topic-exchange #主题交换机
  #配置rabbitmq
  rabbitmq:
    host: 192.168.18.131 #rabbitmq的地址
    port: 5672 #rabbitmq的端口号
    username: admin #rabbitmq的用户名
    password: 123456 #rabbitmq的密码
    virtual-host: dreamcatcher #rabbitmq的虚拟主机

my:
  exchangeName: exchange.topic #交换机名称
  queueAName: queue.topic.a #队列名称
  queueBName: queue.topic.b #队列名称