server:
  port: 8080
spring:
  application:
    name: delay-learn3 #主题交换机
  #配置rabbitmq
  rabbitmq:
#    host: 192.168.18.131 #rabbitmq的地址
    host: 47.120.35.124
    port: 5672 #rabbitmq的端口号
    username: admin #rabbitmq的用户名
    password: 123456 #rabbitmq的密码
    virtual-host: dreamcatcher #rabbitmq的虚拟主机

my:
  exchangeName: exchange.delay.3 #交换机名称
  queueOrderName: queue.delay.normal.order.3 #正常订单队列
  queuePayName: queue.delay.normal.pay.3 #正常支付队列
  queueDlxName: queue.delay.dlx.3 #死信队列名称
