server:
  port: 8080
spring:
  application:
    name: dlx-learn1 #主题交换机
  #配置rabbitmq
  rabbitmq:
    host: 192.168.18.131 #rabbitmq的地址
    port: 5672 #rabbitmq的端口号
    username: admin #rabbitmq的用户名
    password: 123456 #rabbitmq的密码
    virtual-host: dreamcatcher #rabbitmq的虚拟主机

my:
  exchangeNormalName: exchange.normal.a   #正常交换机名称
  queueNormalName: queue.normal.a #正常队列，没有消费者，设置了过期时间
  exchangeDlxName: exchange.dlx.a   #死信交换机名称
  queueDlxName: queue.dlx.a #死信队列
